version: '3.8'

services:
  marxist-chat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /mnt/marxist-chat-data/data/posts_cache:/app/posts_cache
      - /mnt/marxist-chat-data/data/vector_store:/app/vector_store
      - /mnt/marxist-chat-data/data/logs:/app/logs
      - /mnt/marxist-chat-data/models:/app/models
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: 7G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/usr/share/nginx/html/static
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - marxist-chat

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400  # Check for updates once a day
    restart: unless-stopped
    