version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api1:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - REDIS_HOST=redis
      - LLM_SERVICE_URL=http://llm1:5000
      - PORT=8000
      - API_ID=1
    depends_on:
      - redis
      - llm1
    restart: always
    ports:
      - "8001:8000"  # Map container port 8000 to host port 8001
    volumes:
      - ./posts_cache:/app/posts_cache
      - ./vector_store:/app/vector_store
      - ./logs:/app/logs

  api2:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - REDIS_HOST=redis
      - LLM_SERVICE_URL=http://llm2:5000
      - PORT=8000
      - API_ID=2
    depends_on:
      - redis
      - llm2
    restart: always
    ports:
      - "8002:8000"  # Map container port 8000 to host port 8002
    volumes:
      - ./posts_cache:/app/posts_cache
      - ./vector_store:/app/vector_store
      - ./logs:/app/logs

  llm1:
    build:
      context: .
      dockerfile: Dockerfile.llm
    environment:
      - NUM_THREADS=3
      - TEMPERATURE=0.2
      - CURRENT_LLM=https://huggingface.co/bartowski/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    volumes:
      - ./models:/app/models
      - ./vector_store:/app/vector_store
      - ./llm_logs:/app/logs

  llm2:
    build:
      context: .
      dockerfile: Dockerfile.llm
    environment:
      - NUM_THREADS=3
      - TEMPERATURE=0.2
      - CURRENT_LLM=https://huggingface.co/bartowski/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    volumes:
      - ./models:/app/models
      - ./vector_store:/app/vector_store
      - ./llm_logs:/app/logs

volumes:
  redis_data:
