version: '3.8'

services:
  marxist-chat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./posts_cache:/app/posts_cache
      - ./vector_store:/app/vector_store
      - ./logs:/app/logs
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: 7G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
