version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # For HTTPS if you set it up
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - api1
      - api2
    restart: always
    networks:
      - marxist_net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - marxist_net

  api1:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - REDIS_HOST=redis
      - LLM_SERVICE_URL=http://llm1:5000
      - PORT=8000
      - API_ID=1
    depends_on:
      - redis
      - llm1
    restart: always
    # Remove port mapping - Nginx will handle external access
    # ports:
    #   - "8001:8000"
    volumes:
      - ./posts_cache:/app/posts_cache
      - ./vector_store:/app/vector_store
      - ./logs:/app/logs
    networks:
      - marxist_net

  api2:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - REDIS_HOST=redis
      - LLM_SERVICE_URL=http://llm2:5000
      - PORT=8000
      - API_ID=2
    depends_on:
      - redis
      - llm2
    restart: always
    # Remove port mapping - Nginx will handle external access
    # ports:
    #   - "8002:8000"
    volumes:
      - ./posts_cache:/app/posts_cache
      - ./vector_store:/app/vector_store
      - ./logs:/app/logs
    networks:
      - marxist_net

  llm1:
    build:
      context: .
      dockerfile: Dockerfile.llm
    environment:
      - NUM_THREADS=3
      - TEMPERATURE=0.2
      - CURRENT_LLM=https://huggingface.co/bartowski/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf
      - DISTRIBUTED_MODE=false
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    volumes:
      - ./models:/app/models
      - ./vector_store:/app/vector_store:rw
      - ./llm_logs:/app/logs
    networks:
      - marxist_net

  llm2:
    build:
      context: .
      dockerfile: Dockerfile.llm
    environment:
      - NUM_THREADS=3
      - TEMPERATURE=0.2
      - CURRENT_LLM=https://huggingface.co/bartowski/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf
      - DISTRIBUTED_MODE=false
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    volumes:
      - ./models:/app/models
      - ./vector_store:/app/vector_store:rw
      - ./llm_logs:/app/logs
    networks:
      - marxist_net

networks:
  marxist_net:
    driver: bridge

volumes:
  redis_data:
