version: '3'

services:
  marxist-chat:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./posts_cache:/app/posts_cache
      - ./vector_store:/app/vector_store
      - ./logs:/app/logs
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
      - MAX_CONCURRENT_USERS=30
      - QUEUE_TIMEOUT=300
      - REQUEST_TIMEOUT=120
    restart: unless-stopped
    