version: '3.8'

services:
  marxist-chat:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/posts_cache:/app/posts_cache
      - ./data/vector_store:/app/vector_store
      - ./data/logs:/app/logs
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: 7G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./app/static:/usr/share/nginx/html/static
    depends_on:
      - marxist-chat

volumes:
  posts_cache:
    driver: local
  vector_store:
    driver: local
  logs:
    driver: local
    